FROM node:carbon as build
ARG api_host

# Create app directory
WORKDIR /usr/src/pika

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY pika/package*.json ./

# If you are building your code for development:
# RUN npm install
# If you are building your code for production:
RUN yarn install --only=production

RUN yarn add graph-app-kit --registry https://neo.jfrog.io/neo/api/npm/npm


# Bundle app source
COPY pika/ .

EXPOSE 3000