FROM dev-ui as build
RUN REACT_APP_API_HOST=$api_host npm run build  
 
####### Serve site 
FROM nginx 
 
# Remove default website files 
RUN rm -rf /usr/share/nginx/html/* 
 
COPY deployment/default.conf /etc/nginx/conf.d/ 
COPY --from=build /usr/src/pika/build/ /usr/share/nginx/html 
 
EXPOSE 80 
CMD ["nginx", "-g", "daemon off;"]