const ActionTypes = {

  UPDATE_USERNAME: 'UPDATE_USERNAME',
  DATASET_SELECTION: 'DATASET_SELECTION',
  LOAD_DATASETS: 'LOAD_DATASETS',
  LOAD_DATASETS_RESPONSE: 'LOAD_DATASETS_RESPONSE',
  LOGIN: 'LOGIN',
  LOGIN_RESPONSE: 'LOGIN_RESPONSE',
  LOGOUT: 'LOGOUT',
  LOGOUT_RESPONSE: 'LOGOUT_RESPONSE',
  UPDATE_NEW_DATASET_URL: 'UPDATE_NEW_DATASET_URL',
  UPDATE_NEW_DATASET_USERNAME: 'UPDATE_NEW_DATASET_USERNAME',
  UPDATE_NEW_DATASET_PASSWORD: 'UPDATE_NEW_DATASET_PASSWORD',
  SAVE_NEW_DATASET: 'SAVE_NEW_DATASET'
}

export default ActionTypes;
