const ConfigActionTypes = {

  RECEIVE_NODE_TYPES: 'RECEIVE_NODE_TYPES',
  RECEIVE_EDGE_TYPES: 'RECEIVE_EDGE_TYPES',
  CHANGE_EDGE_TYPE_STATE: 'CHANGE_EDGE_TYPE_STATE',
  CHANGE_NODE_TYPE_STATE: 'CHANGE_NODE_TYPE_STATE'
  
}

export default ConfigActionTypes;
