const ExploreActionTypes = {

  FETCH_METAPATHS: 'FETCH_METAPATHS',
  RECEIVE_METAPATHS: 'RECEIVE_METAPATHS',
    SEND_RATED_METAPATHS: 'SEND_RATED_METAPATHS',
    CHANGE_BATCH_SIZE: 'CHANGE_BATCH_SIZE',
    TOGGLE_INTERFACE: ' TOGGLE_INTERFACE',
    CHANGE_RATING: 'CHANGE_RATING',
    CHANGE_MAXPATH_RATING: 'CHANGE_MAXPATH_RATING',
    CHANGE_MINPATH_RATING: 'CHANGE_MINPATH_RATING'
  
}

export default ExploreActionTypes;
