const ResultActionTypes = {

  FETCH_SIMILARITY_SCORE: 'FETCH_SIMILARITY_SCORE',
  RECEIVE_SIMILARITY_SCORE: 'RECEIVE_SIMILARITY_SCORE',
  FETCH_FIRST_NODE_SET_QUERY: 'FETCH_FIRST_NODE_SET_QUERY',
  FETCH_SECOND_NODE_SET_QUERY: 'FETCH_SECOND_NODE_SET_QUERY',
  RECEIVE_FIRST_NODE_SET_QUERY: 'RECEIVE_FIRST_NODE_SET_QUERY',
  RECEIVE_SECOND_NODE_SET_QUERY: 'RECEIVE_SECOND_NODE_SET_QUERY'
  
}

export default ResultActionTypes;
