const ResultActionTypes = {

  FETCH_SIMILARITY_SCORE: 'FETCH_SIMILARITY_SCORE',
  RECEIVE_SIMILARITY_SCORE: 'RECEIVE_SIMILARITY_SCORE',
  FETCH_FIRST_NODE_SET_QUERY: 'FETCH_FIRST_NODE_SET_QUERY',
  FETCH_SECOND_NODE_SET_QUERY: 'FETCH_SECOND_NODE_SET_QUERY',
  RECEIVE_FIRST_NODE_SET_QUERY: 'RECEIVE_FIRST_NODE_SET_QUERY',
  RECEIVE_SECOND_NODE_SET_QUERY: 'RECEIVE_SECOND_NODE_SET_QUERY',
  FETCH_CONTRIBUTING_META_PATHS: 'FETCH_CONTRIBUTING_META_PATHS',
  RECEIVE_CONTRIBUTING_META_PATHS: 'RECEIVE_CONTRIBUTING_META_PATHS',
  FETCH_META_PATH_DETAILS: 'FETCH_META_PATH_DETAILS',
  RECEIVE_META_PATH_DETAILS: 'RECEIVE_META_PATH_DETAILS',
  FETCH_SIMILAR_NODES: 'FETCH_SIMILAR_NODES',
  RECEIVE_SIMILAR_NODES: 'RECEIVE_SIMILAR_NODES'
  
}

export default ResultActionTypes;
