const SetupActionTypes = {

  EXECUTE_CYPHER_QUERY: 'EXECUTE_CYPHER_QUERY',
  ADD_NODES_TO_NODE_SET_A: 'ADD_NODES_TO_NODE_SET_A',
  ADD_NODES_TO_NODE_SET_B: 'ADD_NODES_TO_NODE_SET_B',
  SAVE_NODE_SETS: 'SAVE_NODE_SETS',
  RECEIVE_NODE_SETS: 'RECEIVE_NODE_SETS'
  
}

export default SetupActionTypes;
