const SetupActionTypes = {

  EXECUTE_CYPHER_QUERY: 'EXECUTE_CYPHER_QUERY',
  ADD_NODES_TO_NODE_SET_A: 'ADD_NODES_TO_NODE_SET_A',
  ADD_NODES_TO_NODE_SET_B: 'ADD_NODES_TO_NODE_SET_B'
  
}

export default SetupActionTypes;
